name = "All the Mods 10"
author = "ATMTeam"
version = "6.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4d201b6d954a40b7b84af3b9036b683bec4dfc23f96419203c5ba91822c9de4e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.224"
