name = "All the Mods 10"
author = "ATMTeam"
version = "6.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3cef8a27aecdab74591eebdbb67cbc6089fb731c55e294f159ea3e6e37434f11"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.224"
